"""create_deck_cards_join_table

Revision ID: f1b57ae7f6f6
Revises: cf3b07e54ea4
Create Date: 2022-09-30 08:48:19.782237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b57ae7f6f6'
down_revision = 'cf3b07e54ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], )
    )
    # op.alter_column('cards', 'text',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('deck_cards')
    # ### end Alembic commands ###
